In [9]:
import pandas as pd

In [10]:
# Data Concatenation
# Stacking DataFrames on top of each other(rows) or side by side(columns)

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Eve", "Bob"]
})
df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["Charlie", "Fester", "Gilian"]
    
})

pd.concat([df1, df2]) # row
pd.concat([df1, df2], ignore_index = True)

pd.concat([df1, df2], axis = 1) # column

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian

In [11]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [12]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian